name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        run: |-
          npm install -g md-to-pdf
          mkdir -p _output
          cd test
          echo; echo "Input Folder Listing"
          ls
          echo; echo "Generating PDF"
          cat ./MPM/mpm.md | md-to-pdf > ../_output/mpm.pdf
          cd ../_output
          echo; echo "Output Folder Listing"
          ls
          cd ..
      
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: _output
